// Generated by https://quicktype.io

export interface ILoginRequest {
  username: string;
  password: string;
}

// Generated by https://quicktype.io

export interface ILoginResponse {
    id: number;
    username: string;
    correoElectronico: string;
    accesToken: string;
    refreshToken: string;
}